name: Appium E2E Tests

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to run tests on
        required: true
        default: both
        type: choice
        options:
          - both
          - ios
          - android

concurrency:
  group: appium-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  appium:
    name: Appium
    uses: ./.github/workflows/appium-suite.yml
    with:
      platform: ${{ inputs.platform }}
